# Generated by Django 4.2.3 on 2023-07-11 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('img_url', models.URLField()),
                ('ppg', models.FloatField()),
                ('apg', models.FloatField()),
                ('rpg', models.FloatField()),
                ('spg', models.FloatField()),
                ('bpg', models.FloatField()),
                ('offensive_rating', models.FloatField()),
                ('defensive_rating', models.FloatField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('conference', models.CharField(max_length=100)),
                ('team_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('favorite_team', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_user', to='nbadle.team')),
                ('following_players', models.ManyToManyField(related_name='followers', to='nbadle.player')),
                ('roster', models.ManyToManyField(related_name='user_roster', to='nbadle.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('players', models.ManyToManyField(related_name='userteams', to='nbadle.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nbadle.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nbadle.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(related_name='users', through='nbadle.UserTeam', to='nbadle.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nbadle.team'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_date', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(to='nbadle.user')),
            ],
        ),
    ]
