# Generated by Django 4.2.3 on 2023-07-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbadle', '0002_alter_player_height_alter_player_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='mpg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='tpg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='apg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='bpg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='defensive_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='offensive_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='ppg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='rpg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='spg',
            field=models.FloatField(default=0),
        ),
    ]
