# Generated by Django 4.2.3 on 2023-07-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbadle', '0003_player_mpg_player_tpg_alter_player_apg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='defensive_rating',
            new_name='fg_percent',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='offensive_rating',
            new_name='fpg',
        ),
        migrations.AddField(
            model_name='player',
            name='ft_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='three_pt_percent',
            field=models.FloatField(default=0),
        ),
    ]
